# Generated by Django 3.0.3 on 2020-03-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('file_name', models.CharField(max_length=255)),
                ('link_info', models.TextField()),
                ('painter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Painter')),
            ],
        ),
    ]
