# Generated by Django 3.0.3 on 2020-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='file_name',
        ),
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.FileField(default='', upload_to='pictures'),
        ),
    ]
