# Generated by Django 3.0.3 on 2020-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200303_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(default='', upload_to='static/pictures'),
        ),
    ]
