# Generated by Django 3.0.3 on 2020-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200304_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
