# Generated by Django 3.0.3 on 2020-05-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_picture_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='painter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Painter'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
